### ISSUE TITLE
Setup a proper build system for the server (Java)

### ISSUE THREAD

**Issue by sam46** [sam46/Agar.io-Clone#3]
i.e. Ant, Maven, Gradle

**Comment by mx0c** [comment]
Hey, i would like to help you with this issue... Where did you get the java_websocket.jar? Or did you write it yourself?

**Comment by sam46** [comment]
@mx0c it's this repo
https://github.com/TooTallNate/Java-WebSocket

**Comment by mx0c** [comment]
Send you a PR with a local dependency to your .jar. I've tried to use the newest MavenCentral dependency but i've gotten errors with it. Seems like you did use a pretty old version of that WebSocket. #6 

Happy Hacktoberfest :)
